export default {
  USERS_REPOSITORY: "USERS_REPOSITORY",
  ROLES_REPOSITORY: "ROLES_REPOSITORY",
  USER_ROLES_REPOSITORY: "USER_ROLES_REPOSITORY",
  SAVED_FILTER_REPOSITORY: "SAVED_FILTER_REPOSITORY",
  //LOCALITY_REPOSITORY: "LOCALITY_REPOSITORY",
  //REGION_REPOSITORY: "REGION_REPOSITORY",

  BLOB_REPOSIRORY: "BLOB_REPOSITORY",
  CDN_STORAGE: "blobCache",

};